apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-test-app
  name: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-test-app
  template:
    metadata:
      labels:
        app: node-test-app
    spec:
      containers:
      - image: alx5874/my-repository:node-mongo3
        name: node-mongo
        ports:
          - containerPort: 8080
        env:
          - name: MONGO_URI
            value: "YorMongo"
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: 64Mi
            cpu: 20m
          limits:
            memory: 128Mi
            cpu: 40m
        readinessProbe:
          initialDelaySeconds: 20
          httpGet:
            path: '/api/users'
            port: 8080
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-test-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30475
